### ISSUE TITLE
Can't load config from dynamodb, server crashes on closed connection

### ISSUE THREAD

**Issue by atymic** [soketi/soketi#224]
Hi!

Trying to run latest soketi (0.22) in docker. I've configured the dynamodb table, as well as the AWS creds. I get no error related to the creds, so I assume they are correct, but in the apps section i see the default json config?

When connecting with pusher, get the following message
```
{"event":"pusher:error","data":{"code":4001,"message":"App key <mykey> does not exist."}}
```

This key matches the key in dynamodb. Thinking it might not be loading correctly, I tried the default key, which also fails:
```
{"event":"pusher:error","data":{"code":4001,"message":"App key app-key does not exist."}}
```

Any ideas? Logs below with `debug=1` 👇

```
[29/Dec/2021:01:48:33] {
[29/Dec/2021:01:48:33] adapter: { driver: 'local', redis: { prefix: '' } },
[29/Dec/2021:01:48:33] appManager: {
[29/Dec/2021:01:48:33] driver: 'dynamodb',
[29/Dec/2021:01:48:33] array: {
[29/Dec/2021:01:48:33] apps: [
[29/Dec/2021:01:48:33] {
[29/Dec/2021:01:48:33] id: 'app-id',
[29/Dec/2021:01:48:33] key: 'app-key',
[29/Dec/2021:01:48:33] secret: 'app-secret',
[29/Dec/2021:01:48:33] maxConnections: -1,
[29/Dec/2021:01:48:33] enableClientMessages: false,
[29/Dec/2021:01:48:33] enabled: true,
[29/Dec/2021:01:48:33] maxBackendEventsPerSecond: -1,
[29/Dec/2021:01:48:33] maxClientEventsPerSecond: -1,
[29/Dec/2021:01:48:33] maxReadRequestsPerSecond: -1,
[29/Dec/2021:01:48:33] webhooks: []
[29/Dec/2021:01:48:33] }
[29/Dec/2021:01:48:33] ]
[29/Dec/2021:01:48:33] },
[29/Dec/2021:01:48:33] dynamodb: { table: 'soketi-apps', region: 'ap-southeast-2', endpoint: '' },
[29/Dec/2021:01:48:33] mysql: { table: 'apps', version: '8.0', useMysql2: false },
[29/Dec/2021:01:48:33] postgres: { table: 'apps', version: '13.3' }
[29/Dec/2021:01:48:33] },
[29/Dec/2021:01:48:33] channelLimits: { maxNameLength: 200 },
[29/Dec/2021:01:48:33] cors: {
[29/Dec/2021:01:48:33] credentials: true,
[29/Dec/2021:01:48:33] origin: [ '*' ],
[29/Dec/2021:01:48:33] methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ],
[29/Dec/2021:01:48:33] allowedHeaders: [
[29/Dec/2021:01:48:33] 'Origin',
[29/Dec/2021:01:48:33] 'Content-Type',
[29/Dec/2021:01:48:33] 'X-Auth-Token',
[29/Dec/2021:01:48:33] 'X-Requested-With',
[29/Dec/2021:01:48:33] 'Accept',
[29/Dec/2021:01:48:33] 'Authorization',
[29/Dec/2021:01:48:33] 'X-CSRF-TOKEN',
[29/Dec/2021:01:48:33] 'XSRF-TOKEN',
[29/Dec/2021:01:48:33] 'X-Socket-Id'
[29/Dec/2021:01:48:33] ]
[29/Dec/2021:01:48:33] },
[29/Dec/2021:01:48:33] database: {
[29/Dec/2021:01:48:33] mysql: {
[29/Dec/2021:01:48:33] host: '127.0.0.1',
[29/Dec/2021:01:48:33] port: 3306,
[29/Dec/2021:01:48:33] user: 'root',
[29/Dec/2021:01:48:33] password: 'password',
[29/Dec/2021:01:48:33] database: 'main'
[29/Dec/2021:01:48:33] },
[29/Dec/2021:01:48:33] postgres: {
[29/Dec/2021:01:48:33] host: '127.0.0.1',
[29/Dec/2021:01:48:33] port: 5432,
[29/Dec/2021:01:48:33] user: 'postgres',
[29/Dec/2021:01:48:33] password: 'password',
[29/Dec/2021:01:48:33] database: 'main'
[29/Dec/2021:01:48:33] },
[29/Dec/2021:01:48:33] redis: {
[29/Dec/2021:01:48:33] host: '127.0.0.1',
[29/Dec/2021:01:48:33] port: 6379,
[29/Dec/2021:01:48:33] db: 0,
[29/Dec/2021:01:48:33] username: null,
[29/Dec/2021:01:48:33] password: null,
[29/Dec/2021:01:48:33] keyPrefix: '',
[29/Dec/2021:01:48:33] sentinels: null,
[29/Dec/2021:01:48:33] sentinelPassword: null,
[29/Dec/2021:01:48:33] name: 'mymaster'
[29/Dec/2021:01:48:33] }
[29/Dec/2021:01:48:33] },
[29/Dec/2021:01:48:33] databasePooling: { enabled: false, min: 0, max: 7 },
[29/Dec/2021:01:48:33] debug: 1,
[29/Dec/2021:01:48:33] eventLimits: { maxChannelsAtOnce: 100, maxNameLength: 200, maxPayloadInKb: 100 },
[29/Dec/2021:01:48:33] httpApi: { requestLimitInMb: 100 },
[29/Dec/2021:01:48:33] instance: { process_id: 1 },
[29/Dec/2021:01:48:33] metrics: {
[29/Dec/2021:01:48:33] enabled: false,
[29/Dec/2021:01:48:33] driver: 'prometheus',
[29/Dec/2021:01:48:33] prometheus: { prefix: 'soketi_' },
[29/Dec/2021:01:48:33] port: 9601
[29/Dec/2021:01:48:33] },
[29/Dec/2021:01:48:33] port: 6001,
[29/Dec/2021:01:48:33] pathPrefix: '',
[29/Dec/2021:01:48:33] presence: { maxMembersPerChannel: 100, maxMemberSizeInKb: 2 },
[29/Dec/2021:01:48:33] queue: { driver: 'sync', redis: { concurrency: 1 } },
[29/Dec/2021:01:48:33] rateLimiter: { driver: 'local' },
[29/Dec/2021:01:48:33] ssl: { certPath: '', keyPath: '', passphrase: '' }
[29/Dec/2021:01:48:33] }
[29/Dec/2021:01:48:33] 📡 soketi initialization....
[29/Dec/2021:01:48:33] ⚡ Initializing the HTTP API & Websockets Server...
[29/Dec/2021:01:48:33] ⚡ Initializing the Websocket listeners and channels...
[29/Dec/2021:01:48:33] ⚡ Initializing the HTTP webserver...
[29/Dec/2021:01:48:33] 🕵️‍♂️ Initiating metrics endpoints...
[29/Dec/2021:01:48:33] 🎉 Server is up and running!
[29/Dec/2021:01:48:33] 📡 The Websockets server is available at 127.0.0.1:6001
[29/Dec/2021:01:48:33] 🔗 The HTTP API server is available at http://127.0.0.1:6001
[29/Dec/2021:01:48:33] 🎊 The /usage endpoint is available on port 9601.
[29/Dec/2021:01:49:28] [deployment:4] Reached a steady state
[29/Dec/2021:01:50:07] 👨‍🔬 New connection:
[29/Dec/2021:01:50:07] {
[29/Dec/2021:01:50:07] ws: uWS.WebSocket {
[29/Dec/2021:01:50:07] ip: '172.26.15.238',
[29/Dec/2021:01:50:07] ip2: '',
[29/Dec/2021:01:50:07] appKey: '<key>'
[29/Dec/2021:01:50:07] }
[29/Dec/2021:01:50:07] }
[29/Dec/2021:01:50:17] ❌ Connection closed:
[29/Dec/2021:01:50:17] {
[29/Dec/2021:01:50:17] ws: uWS.WebSocket {
[29/Dec/2021:01:50:17] ip: '172.26.15.238',
[29/Dec/2021:01:50:17] ip2: '',
[29/Dec/2021:01:50:17] appKey: '<key>',
[29/Dec/2021:01:50:17] sendJson: [Function (anonymous)],
[29/Dec/2021:01:50:17] id: '7254798529.1462499284',
[29/Dec/2021:01:50:17] subscribedChannels: Set(0) {},
[29/Dec/2021:01:50:17] presence: Map(0) {}
[29/Dec/2021:01:50:17] },
[29/Dec/2021:01:50:17] code: 1005,
[29/Dec/2021:01:50:17] message: ArrayBuffer { [Uint8Contents]: <>, byteLength: 0 }
[29/Dec/2021:01:50:17] }
[29/Dec/2021:01:50:18] 👨‍🔬 New connection:
[29/Dec/2021:01:50:18] {
[29/Dec/2021:01:50:18] ws: uWS.WebSocket {
[29/Dec/2021:01:50:18] ip: '172.26.15.238',
[29/Dec/2021:01:50:18] ip2: '',
[29/Dec/2021:01:50:18] appKey: '<key>'
[29/Dec/2021:01:50:18] }
[29/Dec/2021:01:50:18] }
[29/Dec/2021:01:50:36] /app/dist/ws-handler.js:26
[29/Dec/2021:01:50:36] if (ws.send(JSON.stringify(data))) {
[29/Dec/2021:01:50:36] ^
[29/Dec/2021:01:50:36] Error: Invalid access of closed uWS.WebSocket/SSLWebSocket.
[29/Dec/2021:01:50:36] at uWS.WebSocket.ws.sendJson (/app/dist/ws-handler.js:26:20)
[29/Dec/2021:01:50:36] at /app/dist/ws-handler.js:52:20
[29/Dec/2021:01:50:36] at processTicksAndRejections (node:internal/process/task_queues:96:5)
[29/Dec/2021:01:50:42] 🚫 New users cannot connect to this instance anymore. Preparing for signaling...
[29/Dec/2021:01:50:42] ⚡ The server is closing and signaling the existing connections to terminate.
[29/Dec/2021:01:50:42] ⚡ All sockets were closed. Now closing the server.
```

**Comment by rennokki** [comment]
I think it's because of the AWS authentication. What method did you use?

**Comment by atymic** [comment]
AWS keys via env vars. I'll have a go and double check that the keys work for dynamodb directly, but they are definitely passed. Maybe the app should validate that creds are passed, or at least an error if they are wrong?

![Screen Shot 2022-01-13 at 11 08 55](https://user-images.githubusercontent.com/50683531/149242733-3710ea1f-bf16-4f22-a1c2-2475f2f03755.png)

**Comment by atymic** [comment]
Hmm, I double checked and it seems that the creds are correct. The AWS dash reported they were never used (despite being passed correctly to the docker container, double checked).

I was able to use them via a test node app to list the dynamo tables and add records without any issues.
