### ISSUE TITLE
Allow TLS for Redis connection

### ISSUE THREAD

**Issue by stayallive** [soketi/soketi#225]
We are using a managed database by Digital Ocean and they require an SSL connection. AWS ElastiCache and many other managed solutions have the same requirement.

This is "easy" to enable by adding a `tls: {}` to the options passed to `new Redis({...})`. However I have a hard time figuring out how to do this nicely so we can have a `DB_REDIS_TLS=true` and it doing `tls: {}` or `tls: undefined` (which is the default) based on that value. Any help would be appreciated :)

I also noticed that when Redis has a connection problem it spins out of control (consuming ~1 core of CPU time) in an infinite loop barfing this when in debug mode:

```
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Redis.sendCommand (/usr/lib/node_modules/@soketi/soketi/node_modules/ioredis/built/redis/index.js:672:33)
    at /usr/lib/node_modules/@soketi/soketi/node_modules/ioredis/built/redis/event_handler.js:256:26
    at Socket.<anonymous> (/usr/lib/node_modules/@soketi/soketi/node_modules/ioredis/built/redis/event_handler.js:46:39) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: write ECONNRESET
    at afterWriteDispatched (node:internal/stream_base_commons:164:15)
    at writeGeneric (node:internal/stream_base_commons:155:3)
    at Socket._writeGeneric (node:net:795:11)
    at Socket._write (node:net:807:8)
    at writeOrBuffer (node:internal/streams/writable:389:12)
    at _write (node:internal/streams/writable:330:10)
    at Socket.Writable.write (node:internal/streams/writable:334:10)
    at Redis.sendCommand (/usr/lib/node_modules/@soketi/soketi/node_modules/ioredis/built/redis/index.js:672:33)
    at /usr/lib/node_modules/@soketi/soketi/node_modules/ioredis/built/redis/event_handler.js:256:26
    at Socket.<anonymous> (/usr/lib/node_modules/@soketi/soketi/node_modules/ioredis/built/redis/event_handler.js:46:39) {
  errno: -104,
  code: 'ECONNRESET',
  syscall: 'write'
}
```

Maybe we should have a little more conservatie [retry strategy](https://github.com/luin/ioredis#auto-reconnect).

**Comment by rennokki** [comment]
I think I'll start implementing support for JSON-based configurations as files. This way it's better to configure nested values 🤔  (https://github.com/soketi/soketi/projects/1#card-64718909)

**Comment by rennokki** [comment]
I think that environment variables wouldn't be a great choice for complex configurations. I don't really know why I started doing that in the first place, but having a JSON file that can be configured would be easier.

```json
{
    "database.redis.tls": { ... }
}
```

```bash
soketi start --config=/path/to/config.json
```

**Comment by stayallive** [comment]
Honestly having it makes setting up a server really quick and easy... so I like having the JSON option but would not call the env variables bad honestly.

Also for the TLS option, it just needs to be an empty object so there is not much to configure unless you also want to implement reading files from disk.

**Comment by rennokki** [comment]
Still going to work on this to make env variables for this a thing 🤔

**Comment by mackensiealvarezz** [comment]
Is there any way of doing this with environment variables ?

**Comment by stayallive** [comment]
No it is not, but it's very easy to do with the JSON (in addition to your environment variables).

Create a files called `config.json` on your server which should be accessible by the user running Soketi with the following contents:

```json
{
    "database.redis.tls": {}
}
```

Instead of running just `soketi start`, change it to `soketi start --config=/home/soketi/config.json` and then you can use a Redis host using TLS (like a Digital Ocean managed Redis instance).

**Comment by rennokki** [comment]
I had to postpone this issue. For now, the config should work perfectly fine.

**Comment by mackensiealvarezz** [comment]
I'm using the docker image inside of my helm chart. How can I pass this command? It looks like the command automatically runs when the container starts.

I tried this but it didn't work

```
        - name: soketi
          image: quay.io/soketi/soketi:0.32.2-16-alpine
          command:
            - node
            - /app/bin/server.js
            - start --config=/etc/configws/config.json

**Comment by rennokki** [comment]
Have you injected the file in the pod?

**Comment by mackensiealvarezz** [comment]
Yes, I created a custom configmap with:
```
{
    "database.redis.tls": {}
}

and mounted it to /etc/configws/config.json

I also exec into the pod and confirmed the file was there. I tried to also exec into the pod and run node server.js start --config=/etc/configws/config.json. When i did that, the pod just terminates and crashes

**Comment by winfamy** [comment]
@mackensiealvarezz I FIGURED YOUR ISSUE OUT
I've been going through this myself trying to figure out how to do this (TLS on Redis)

```
        - name: soketi
          image: quay.io/soketi/soketi:0.32.2-16-alpine
          command:
            - node
            - /app/bin/server.js
            - start --config=/etc/configws/config.json
```
is an incorrect way of specifying the command block for a docker-compose config. Instead, you need to separate your last line!!!!!

```
        - name: soketi
          image: quay.io/soketi/soketi:0.32.2-16-alpine
          command:
            - node
            - /app/bin/server.js
            - start 
            - --config=/etc/configws/config.json
```
This worked for me!

(sorry unrelated to issue at hand, but will prevent someone from troubleshooting docker + soketi for a few hours)

**Comment by reesmcivor** [comment]
Would you mind providing the full docker-compose file? I have been trying for a while to pass a config file through but no luck as of yet.

**Comment by reesmcivor** [comment]
Hi there, I'm pleased I've found this thread. I'm having some difficulties passing the config file using docker-compose. Could you possibly share your final docker-compose file.

The one I have is below: 
`version: '3.9'
services:
  soketi:
    container_name: 'soketi_server'
    restart: unless-stopped
    image: quay.io/soketi/soketi:0.32.2-16-alpine
    command:
      - node
      - /app/bin/server.js
      - start 
      - --config=/etc/configws/config.json
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    networks:
      - soketi_network
    volumes:
      - /home/ploi:/app/ploi

networks:
  soketi_network:
    driver: bridge`

**Comment by limadelrey** [comment]
Is there any update on allowing to configure TLS using an environment variable? ☝️
