### ISSUE TITLE
deploy on server CentOS

### ISSUE THREAD

**Issue by farshidpg** [soketi/soketi#281]
when i rum soketi start :

```
/usr/lib/node_modules/@soketi/soketi/node_modules/uWebSockets.js/uws.js:22
                throw new Error('This version of µWS is not compatible with your Node.js build:\n\n' + e.toString());
                ^

Error: This version of µWS is not compatible with your Node.js build:

Error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /usr/lib/node_modules/@soketi/soketi/node_modules/uWebSockets.js/uws_linux_x64_102.node)
    at /usr/lib/node_modules/@soketi/soketi/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/usr/lib/node_modules/@soketi/soketi/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/usr/lib/node_modules/@soketi/soketi/dist/server.js:17:13)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)

Node.js v17.3.0
```

**Comment by rennokki** [comment]
CentOS is not supported: https://github.com/uNetworking/uWebSockets.js/issues/500

**Comment by malohtie** [comment]
@rennokki can you please mention this in readme or docs thanks

**Comment by malohtie** [comment]
Yes, wasted half of the day trying to figure why it isn't installing on centos 7 xD
at the end i was forced to use docker as i have no choice left

**Comment by rennokki** [comment]
Sorry for misleading the installation process. I have fixed later that day the installation process' details. 😁
