### ISSUE TITLE
How to add a config file with the supervisor?

### ISSUE THREAD

**Issue by hsndmr** [soketi/soketi#307]
I want to add a config file with a config argument using the supervisor. I created "soketi.conf" and I defined a path using config argument then I executed "sudo supervisorctl start soketi:*" command, but it did not work and throw an error soketi:soketi_00: ERROR (no such file)"

````
[program:soketi]
process_name=%(program_name)s_%(process_num)02d
command=soketi start --config="/home/ubuntu/soketi/config.json"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=ubuntu
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/soketi-supervisor.log
stopwaitsecs=60
stopsignal=sigint
minfds=10240
````

**Comment by hsndmr** [comment]
@rennokki 

I have tried, it is throwed same error.
> Have you tried setting the `command` like below (i wrapped everything in `"`)?
> 
> ```diff
> - command=soketi start --config="/home/ubuntu/soketi/config.json"
> + command="soketi start --config=/home/ubuntu/soketi/config.json"
> ```

**Comment by rennokki** [comment]
The command is run as `user=ubuntu`, make sure the `ubuntu` user has access to the file.

**Comment by hsndmr** [comment]
@rennokki 
if i use command=soketi start this comand, it is working. ubuntu user is accessing to the config file.

**Comment by rkrater** [comment]
Same issue - runs fine if i take out the --config or run it outside of supervisor

supervisord.log contains : 
`INFO spawnerr: can't find command 'soketi start --config=/etc/soketi/config.json'`

**Comment by rbruhn** [comment]
I thought one way to handle this issue was using a .env file. So, the supervisor conf would look like:

`[program:soketi]
process_name=%(program_name)s_%(process_num)02d
directory=/path_to_env_directory/
command=soketi start
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=vagrant
numprocs=1
redirect_stderr=true
stdout_logfile=/var/log/supervisor/prod/soketi.log
stopwaitsecs=60
stopsignal=sigint
minfds=10240`

.env file
`DEFAULT_APP_ID=myappid
DEFAULT_APP_KEY=mykey
DEFAULT_APP_SECRET=mysecret

SOKETI_DEBUG=1
SSL_CERT="/etc/ssl/certs/domain.test.crt"
SSL_KEY="/etc/ssl/certs/domain.test.key"`

However, I get the following error when Soketi is starting whether it's from Supervisor or CLI.

`📡 soketi initialization....

⚡ Initializing the HTTP API & Websockets Server...

(node:8038) UnhandledPromiseRejectionWarning: Error: App construction failed
    at /usr/lib/node_modules/@soketi/soketi/dist/server.js:212:23
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:8038) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8038) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[Fri Feb 04 2022 15:43:58 GMT+0000 (Coordinated Universal Time)] Promoted from node to master.
{
  isMaster: true,
  isMasterEligible: true,
  weight: -0.1643989438275,
  address: '127.0.0.1',
  advertisement: undefined
}

`

**Comment by hsndmr** [comment]
@rbruhn If you need 3 app, how could you fix it?

**Comment by rbruhn** [comment]
@hsndmr If you mean adding apps to the AppManager like below, then not sure you can. My situation was only running one app.

One solution would be for @rennokki to make Soketi look for either the config or env on start up instead of needing to reference it. I played with trying to pass a json object string in my env (dirty solution) but it didn't work.


```
{
    "appManager.array.apps.0.id": "some-id",
    "appManager.array.apps.0.key": "some-key",
    "appManager.array.apps.0.secret": "some-secret",
    "appManager.array.apps.0.webhooks": [{
        "url": "https://...",
        "event_types": ["channel_occupied"],
    }],
    "debug": true,
    "port": 6002
}
```

**Comment by andreaspabst** [comment]
Supervisord is telling me:
 `soketi:soketi_00                 FATAL     can't find command 'soketi'`

What could be the issue in this case? Supervisor seems to not see my npm global packages

**Comment by hsndmr** [comment]
@andreaspabst  How did you install the soketi?. If you want to run it with the supervisor, you should install it running npm install -g soketi.

**Comment by diadal** [comment]
on M1 mac create `test.sh` file `/usr/local/bin/node` `/usr/local/bin/soketi ` `start` `--config=/opt/homebrew/var/www/sites-backend/config.json`

```
#!/bin/bash
/usr/local/bin/node /usr/local/bin/soketi start  --config=/opt/homebrew/var/www/sites-backend/config.json
```

`supervisor `


```
[program:soketi-kr]
command=/opt/homebrew/var/www/Sites/sites-backend/cmd/test.sh
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=administrator
numprocs=1
redirect_stderr=true
stderr_logfile=/opt/homebrew/var/www/Sites/sites-backend/storage/logs/soketi-supervisor.err.log
stdout_logfile=/opt/homebrew/var/www/Sites/sites-backend/storage/logs/soketi-supervisor.log
stopwaitsecs=60
stopsignal=sigint
minfds=10240
```

`config.json`

```
{
    "debug": false,
    "port": 6010,
    "appManager.array.apps": [
        {
            "id": "******",
            "key": "cd8*****",
            "secret": "716ba******",
            "cluster": "us2"
        }
    ]
}
```
