### ISSUE TITLE
[bug] EACCES: permission denied, mkdir '/etc/.pm2/logs'

### ISSUE THREAD

**Issue by ahoiroman** [soketi/soketi#367]
Hello,

I got a little problem using soketi on **Laravel Forge**.

I followed this article (https://blog.laravel.com/deploying-soketi-to-laravel-forge) to configure a daemon that makes sure that soketi is always up and running.

This is the resulting daemon:

<img width="995" alt="Bildschirmfoto 2022-02-17 um 09 37 15@2x" src="https://user-images.githubusercontent.com/23051150/154437275-40a46513-06e4-4156-95a1-ad670e5ca171.png">

And this is the generated supervisord-config:

```
[program:daemon-674304]
command=soketi start --config=/home/forge/soketi.json

process_name=%(program_name)s_%(process_num)02d
autostart=true
autorestart=true
user=forge
numprocs=1
startsecs=1
redirect_stderr=true
stdout_logfile=/home/forge/.forge/daemon-674304.log
stopwaitsecs=60
stopsignal=SIGINT
stopasgroup=true
killasgroup=true
```

Now I am getting this error on startup:

```
[PM2][Initialization] Environment variable HOME (Linux) or HOMEPATH (Windows) are not set!
[PM2][Initialization] Defaulting to /etc/.pm2
Error: EACCES: permission denied, mkdir '/etc/.pm2/logs'
    at Object.mkdirSync (fs.js:1013:3)
    at mkdirpNativeSync (/usr/lib/node_modules/@soketi/soketi/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/usr/lib/node_modules/@soketi/soketi/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/Client.js:133:25)
    at new module.exports (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/Client.js:38:8)
    at new API (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
Error: EACCES: permission denied, mkdir '/etc/.pm2/pids'
    at Object.mkdirSync (fs.js:1013:3)
    at mkdirpNativeSync (/usr/lib/node_modules/@soketi/soketi/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/usr/lib/node_modules/@soketi/soketi/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/Client.js:141:25)
    at new module.exports (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/Client.js:38:8)
    at new API (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
Error: ENOENT: no such file or directory, open '/etc/.pm2/module_conf.json'
    at Object.openSync (fs.js:497:3)
    at Object.writeFileSync (fs.js:1528:35)
    at module.exports.Client.initFileStructure (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/Client.js:149:10)
    at new module.exports (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/Client.js:38:8)
    at new API (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
Error: EACCES: permission denied, mkdir '/etc/.pm2/modules'
    at Object.mkdirSync (fs.js:1013:3)
    at mkdirpNativeSync (/usr/lib/node_modules/@soketi/soketi/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/usr/lib/node_modules/@soketi/soketi/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/Client.js:157:25)
    at new module.exports (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/Client.js:38:8)
    at new API (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/API.js:108:19)
    at Object.<anonymous> (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
Error: ENOENT: no such file or directory, open '/etc/.pm2/module_conf.json'
    at Object.openSync (fs.js:497:3)
    at Object.readFileSync (fs.js:393:35)
    at Object.Configuration.getAllSync (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/Configuration.js:299:26)
    at Object.Configuration.getSync (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/Configuration.js:270:30)
    at new API (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/lib/API.js:117:44)
    at Object.<anonymous> (/usr/lib/node_modules/@soketi/soketi/node_modules/pm2/index.js:11:18)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
```

Any help or hint is highly appreciated :-)

**Comment by rennokki** [comment]
You may want to run it as root or see this fix: https://github.com/Unitech/pm2/issues/487

**Comment by Christophvh** [comment]
I got the same issue and I solved it by specifying the forge directory to an actual site directory.

**Comment by ahoiroman** [comment]
Hi Christoph,

thanks for your update. I got a question about that: What do you mean with "specifying the forge director to an actual site directory"? The "forge directory" should be `/home/forge`, right?

So did you set the working directory in Laravel Forge to `/home/forge/default`, as it's the site-dir for the user?

**Comment by zainzulifqargit** [comment]
### Try this

```sudo -u forge soketi start --config=/home/forge/config.json```

**Comment by Diz-X** [comment]
> You may want to run it as root or see this fix: [Unitech/pm2#487](https://github.com/Unitech/pm2/issues/487)

Running as root is BAD security practice. 

This issue is not a soketi problem, more a  pm2 problem. 

I use supervisord to monitor and control the soketi processes. To fix the issue with this error with supervisord, you should add the following to you supervisord config:

```
[program:soketi]
...
environment=HOME="/home/soketi"
```

In this case I created a user called "soketi" with nologin and with a home directory.

**Comment by rennokki** [comment]
Gonna close this up. @Diz-X's solution is working to me too.

**Comment by MaksOn-dev** [comment]
Thanks  @Diz-X's, I finally solved my problem.

Note for others: if you do not get rid of this errors Soketi can work unstable. From time-to-time my events haven't been received by frontend thought it was sent from backend. I didn't understand why it happening until fixed this issues

**Comment by hosni** [comment]
I ran into the same “**EACCES**: **permission denied**, mkdir `/etc/.pm2/logs` error.

I solved it by mounting a [tmpfs](https://docs.docker.com/engine/storage/tmpfs/) for the PM2 home directory, so that it’s writable (in memory) and doesn’t try to write under `/etc`.

Here’s my Docker Compose snippet:
```yaml
soketi:
  image: quay.io/soketi/soketi:1.4-16-distroless
  restart: always
  environment:
    PM2_HOME: '/app/.pm2'
  tmpfs:
    - /app/.pm2:noexec,size=10m,mode=1777
```

With that:
* The `PM2_HOME` env var ensures PM2 uses `/app/.pm2` instead of `/etc/.pm2`.
* The `tmpfs` mount gives a writable ephemeral filesystem (10 MB here) at `/app/.pm2`, with `1777` mode so it’s world-writable (sticky bit).
* Thus PM2 can create logs, pids, etc. without permission issues.

Or you can run it using `docker run` with:
```bash
docker run -p 6001:6001 -e PM2_HOME="/app/.pm2" --tmpfs /app/.pm2:noexec,size=1024,mode=1777 quay.io/soketi/soketi:1.4-16-distroless
```
