### ISSUE TITLE
Shutdown TypeError: Cannot read properties of undefined (reading 'disconnect')

### ISSUE THREAD

**Issue by rolandstarke** [soketi/soketi#453]
Hey,

Just a minor inconvenience.

When running the following commands

```bash
composer create-project laravel/laravel example-app
cd example-app
soketi start
```

You get the following output
```bash
PS D:\MyStuff\programmieren\example-app> soketi start

  Cache driver not set.  
  🕵️‍♂️ Initiating metrics endpoints...   

   🎉 Server is up and running!   
   📡 The Websockets server is available at 127.0.0.1:6001        
   🔗 The HTTP API server is available at http://127.0.0.1:6001   
   🎊 The /usage endpoint is available on port 9601.   
```

Note The: "Cache driver not set." I guess thats because Laravel has `CACHE_DRIVER=file` in their .env. And that does not exist in siketi.

When ending the soketi server you get an error:

```bash
C:\Users\Roland\AppData\Roaming\npm\node_modules\@soketi\soketi\dist\cache-managers\cache-manager.js:26
        return this.driver.disconnect();
                           ^

TypeError: Cannot read properties of undefined (reading 'disconnect')
    at CacheManager.disconnect (C:\Users\Roland\AppData\Roaming\npm\node_modules\@soketi\soketi\dist\cache-managers\cache-manager.js:26:28)
    at Timeout._onTimeout (C:\Users\Roland\AppData\Roaming\npm\node_modules\@soketi\soketi\dist\server.js:304:43)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

Would be cool if worked out of the box with the default laravel `.env`.

**Comment by rennokki** [comment]
Ah yes, you got a `CACHE_DRIVER` in your `.env`?

**Comment by rolandstarke** [comment]
Yes.

https://github.com/laravel/laravel/blob/039a99ad14dbb6cfebb6a04be4679f0916f639a4/.env.example#L19

**Comment by rennokki** [comment]
The fix will be in https://github.com/soketi/soketi/pull/452

As a temporary workaround, run soketi from other folder than your project.

**Comment by rennokki** [comment]
@rolandstarke It was merged in 1.x, you might want to migrate. Please read the migration guide: https://docs.soketi.app/v/1.x/getting-started/upgrading-from-0.x
