### ISSUE TITLE
Cannot read property 'enabled' of undefined.

### ISSUE THREAD

**Issue by zainzulifqargit** [soketi/soketi#482]
**command i am running:**
``sudo -u forge soketi start --config=/home/forge/config.json``

**Error msg:**
```
   🕵️‍♂️ Initiating metrics endpoints...  
   🎉 Server is up and running!   
   📡 The Websockets server is available at 127.0.0.1:6001   
   🔗 The HTTP API server is available at http://127.0.0.1:6001   
   🎊 The /usage endpoint is available on port 9601.   

/usr/lib/node_modules/@soketi/soketi/dist/app-managers/app-manager.js:43
        if (!this.server.options.appManager.cache.enabled) {
                                                  ^

TypeError: Cannot read property 'enabled' of undefined
    at AppManager.findByKey (/usr/lib/node_modules/@soketi/soketi/dist/app-managers/app-manager.js:43:51)
    at WsHandler.checkForValidApp (/usr/lib/node_modules/@soketi/soketi/dist/ws-handler.js:437:39)
    at WsHandler.onOpen (/usr/lib/node_modules/@soketi/soketi/dist/ws-handler.js:53:14)
    at open (/usr/lib/node_modules/@soketi/soketi/dist/server.js:437:50)
    at WsHandler.handleUpgrade (/usr/lib/node_modules/@soketi/soketi/dist/ws-handler.js:192:13)
    at upgrade (/usr/lib/node_modules/@soketi/soketi/dist/server.js:439:68)

```

### Config File:

```
{
    "adapter": {
        "driver": "local"
    },
    "appManager": {
        "driver": "array",
        "array": {
            "apps": [
                {
                    "id": "app-id",
                    "key": "app-key",
                    "secret": "app-secret",
                    "maxConnections": -1,
                    "enableClientMessages": false,
                    "enabled": true,
                    "maxBackendEventsPerSecond": -1,
                    "maxClientEventsPerSecond": -1,
                    "maxReadRequestsPerSecond": -1,
                    "webhooks": []
                },
            ]
        }
    }
}
```

**Comment by zainzulifqargit** [comment]
after using this in config file its working:

```
{
    "appManager.array.apps": [
      {
        "id": "app-id",
        "key": "app-key",
        "secret": "app-secret",
        "maxConnections": -1,
        "enableClientMessages": false,
        "enabled": true,
        "maxBackendEventsPerSecond": -1,
        "maxClientEventsPerSecond": -1,
        "maxReadRequestsPerSecond": -1,
        "webhooks": []
      },
      {
        "id": "app-id-two",
        "key": "app-key-two",
        "secret": "app-secret-two",
        "maxConnections": -1,
        "enableClientMessages": false,
        "enabled": true,
        "maxBackendEventsPerSecond": -1,
        "maxClientEventsPerSecond": -1,
        "maxReadRequestsPerSecond": -1,
        "webhooks": []
      }
    ]
 }
 ```

**Comment by rennokki** [comment]
It's not recommended to use nested keys by nested declaration. The dot notation is fixing issues for the nested notation. That's why the second one works.
