### ISSUE TITLE
[bug] Access of discarded response race condition

### ISSUE THREAD

**Issue by atymic** [soketi/soketi#569]
This seems to happen every few weeks, crashing the server. Causes a bunch of notifications in my error monitor as event broadcasting fails, while the node restarts.

Not sure exactly what causes the issue, but seems to happen when high traffic is being send to the HTTP side.

```
[21/Jun/2022:00:31:23] /app/dist/http-handler.js:475
[21/Jun/2022:00:31:23] return res.writeStatus(status)
[21/Jun/2022:00:31:23] ^
[21/Jun/2022:00:31:23] Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
[21/Jun/2022:00:31:23] at HttpHandler.sendJson (/app/dist/http-handler.js:475:20)
[21/Jun/2022:00:31:23] at HttpHandler.badResponse (/app/dist/http-handler.js:302:21)
[21/Jun/2022:00:31:23] at /app/dist/http-handler.js:329:25
```

Version: `quay.io/soketi/soketi:1.2.0-16-debian`

**Comment by atymic** [comment]
Again yesterday:

```
[7/Jul/2022:03:46:25] /app/dist/http-handler.js:486
[7/Jul/2022:03:46:25] return res.writeStatus(status)
[7/Jul/2022:03:46:25] ^
[7/Jul/2022:03:46:25] Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
[7/Jul/2022:03:46:25] at HttpHandler.sendJson (/app/dist/http-handler.js:486:20)
[7/Jul/2022:03:46:25] at HttpHandler.badResponse (/app/dist/http-handler.js:313:21)
[7/Jul/2022:03:46:25] at /app/dist/http-handler.js:340:25
[7/Jul/2022:03:47:59] 🕵️‍♂️ Initiating metrics endpoints...
[7/Jul/2022:03:47:59] 🎉 Server is up and running!
[7/Jul/2022:03:47:59] 📡 The Websockets server is available at 127.0.0.1:6001
[7/Jul/2022:03:47:59] 🔗 The HTTP API server is available at http://127.0.0.1:6001
[7/Jul/2022:03:47:59] 🎊 The /usage endpoint is available on port 9601.
```

**Comment by atymic** [comment]
Seems to happen when there's a spike of requests, but nothing the server should be struggling with

![Screen Shot 2022-07-11 at 10 36 38](https://user-images.githubusercontent.com/50683531/178168907-05658187-155d-4a04-be30-6398390bf54c.png)


```
[10/Jul/2022:06:38:48] /app/dist/http-handler.js:486
[10/Jul/2022:06:38:48] return res.writeStatus(status)
[10/Jul/2022:06:38:48] ^
[10/Jul/2022:06:38:48] Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
[10/Jul/2022:06:38:48] at HttpHandler.sendJson (/app/dist/http-handler.js:486:20)
[10/Jul/2022:06:38:48] at HttpHandler.badResponse (/app/dist/http-handler.js:313:21)
[10/Jul/2022:06:38:48] at /app/dist/http-handler.js:340:25
[10/Jul/2022:06:40:23] 🕵️‍♂️ Initiating metrics endpoints...
[10/Jul/2022:06:40:23] 🎉 Server is up and running!
[10/Jul/2022:06:40:23] 📡 The Websockets server is available at 127.0.0.1:6001
[10/Jul/2022:06:40:23] 🔗 The HTTP API server is available at http://127.0.0.1:6001
[10/Jul/2022:06:40:23] 🎊 The /usage endpoint is available on port 9601.
```

**Comment by atymic** [comment]
Thanks, will update to new release!

**Comment by rennokki** [comment]
@atymic Let me know if this still persists.

**Comment by atymic** [comment]
Thanks, upgraded and yet to see any issues. WIll reach out if it happens but looks good so far :)

**Comment by stayallive** [comment]
@atymic have you seen the issue again since the fixes? Otherwise I think we can close this as fixed 😎

**Comment by atymic** [comment]
Since 1.4.0 seems to have been fine, can close! Thanks.
Just updated to 1.5.0 as well.

**Comment by atymic** [comment]
@rennokki have noticed some more of these errors on 1.5.0. Just updated to 1.6.0, will see if the issue persists.

```
[31/Aug/2023:23:12:58] [Thu Aug 31 2023 23:12:58 GMT+0000 (Coordinated Universal Time)] Response could not be sent
[31/Aug/2023:23:12:58] Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
[31/Aug/2023:23:12:58] at HttpHandler.sendJson (/app/dist/http-handler.js:497:24)
[31/Aug/2023:23:12:58] at /app/dist/http-handler.js:213:22
[31/Aug/2023:23:12:58] at runMicrotasks (<anonymous>)
[31/Aug/2023:23:12:58] at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by atymic** [comment]
@rennokki still having this issue. See below from latest version

```
[20/Sept/2023:01:03:10] [Wed Sep 20 2023 01:03:10 GMT+0000 (Coordinated Universal Time)] Response could not be sent
[20/Sept/2023:01:03:10] Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
[20/Sept/2023:01:03:10] at HttpHandler.sendJson (/app/dist/http-handler.js:497:24)
[20/Sept/2023:01:03:10] at HttpHandler.badResponse (/app/dist/http-handler.js:324:21)
[20/Sept/2023:01:03:10] at /app/dist/http-handler.js:351:25
[20/Sept/2023:01:05:41] [Wed Sep 20 2023 01:05:41 GMT+0000 (Coordinated Universal Time)] Response could not be sent
[20/Sept/2023:01:05:41] Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
[20/Sept/2023:01:05:41] at HttpHandler.sendJson (/app/dist/http-handler.js:497:24)
[20/Sept/2023:01:05:41] at /app/dist/http-handler.js:213:22
[20/Sept/2023:01:05:41] at runMicrotasks (<anonymous>)
[20/Sept/2023:01:05:41] at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by atymic** [comment]
Happening still

```
[27/Feb/2024:07:09:25] [Tue Feb 27 2024 07:09:25 GMT+0000 (Coordinated Universal Time)] Response could not be sent
[27/Feb/2024:07:09:25] Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
[27/Feb/2024:07:09:25] at HttpHandler.sendJson (/app/dist/http-handler.js:497:24)
[27/Feb/2024:07:09:25] at HttpHandler.badResponse (/app/dist/http-handler.js:324:21)
[27/Feb/2024:07:09:25] at /app/dist/http-handler.js:351:25
[27/Feb/2024:07:12:25] [Tue Feb 27 2024 07:12:25 GMT+0000 (Coordinated Universal Time)] Response could not be sent
[27/Feb/2024:07:12:25] Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
[27/Feb/2024:07:12:25] at uWS.HttpResponse.writeStatus (<anonymous>)
[27/Feb/2024:07:12:25] at HttpHandler.sendJson (/app/dist/http-handler.js:497:24)
[27/Feb/2024:07:12:25] at /app/dist/http-handler.js:213:22
[27/Feb/2024:07:12:25] at runMicrotasks (<anonymous>)
[27/Feb/2024:07:12:25] at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by harshv1995** [comment]
Still happening,
```
Error: Invalid access of discarded (invalid, deleted) uWS.HttpResponse/SSLHttpResponse.
    at HttpHandler.sendJson (/app/dist/http-handler.js:486:20)
    at HttpHandler.badResponse (/app/dist/http-handler.js:313:21)
    at /app/dist/http-handler.js:340:25
```
