### ISSUE TITLE
[BUG] Error and Connection Looping during server stop in 1.4.0

### ISSUE THREAD

**Issue by roman-supy-io** [soketi/soketi#669]
**Description**
In the latest version, when the server that's using `Redis/MySQL` is stopped it creates many connections and then exits with an Error.

_This only happens with the actual app (db-stored) AND on version `1.4.0`. On `1.3.0` there's no Connection Looping, but the Error on stop still exists. Strange enough, `1.2.0` is completely free of both of those problems._

```js
/Users/***/Code/GitHub/soketi-chat/node_modules/ioredis/built/redis/event_handler.js:182
        self.flushQueue(new Error(utils_1.CONNECTION_CLOSED_ERROR_MSG));
                        ^

Error: Connection is closed.
    at close (/Users/***/Code/GitHub/soketi-chat/node_modules/ioredis/built/redis/event_handler.js:182:25)
    at Socket.<anonymous> (/Users/***/Code/GitHub/soketi-chat/node_modules/ioredis/built/redis/event_handler.js:149:20)
    at Object.onceWrapper (node:events:510:26)
    at Socket.emit (node:events:390:28)
    at Socket.emit (node:domain:475:12)
    at TCP.<anonymous> (node:net:687:12)
```

**Reproduction steps**
1. Clone the repo at [https://github.com/roman-supy-io/soketi-chat](https://github.com/roman-supy-io/soketi-chat)
2. Open in your favourite editor
3. Have a local MySQL instance running, run this script against db name: `mysql`, table: `apps` to insert an app:
   ```sql
   INSERT INTO `apps` (`id`, `key`, `secret`, `max_connections`, `enable_client_messages`, `enabled`, `max_backend_events_per_sec`, `max_client_events_per_sec`, `max_read_req_per_sec`, `webhooks`, `max_presence_members_per_channel`, `max_presence_member_size_in_kb`, `max_channel_name_length`, `max_event_channels_at_once`, `max_event_name_length`, `max_event_payload_in_kb`, `max_event_batch_size`, `enable_user_authentication`) VALUES ("chat", "0d81cd6d4bcbb4a9eaac", "3652d38a50001e7f0200", -1, 1, 1, -1, -1, -1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 1);
   ```
4. You'll need to run several terminal windows to achieve this.
After you cloned, `cd soketi-chat`, 'npm install' and:
  a. Start Redis: `redis-server`
  b. Start Soketi `npm run soketi`
  c. Start API: `npx nx run api`
  d. Start APP: `npx nx run app`
5. Visit `localhost:4200` to init a connection
6. Open terminal from `4. b.`, press `Ctrl+C` and watch hundreds of new requests being created.
7. Check the browser tab at `localhost:4200` to verify the connections are there too.

`HINT:` to check how the Pusher SDK's are configured, see:
https://github.com/roman-supy-io/soketi-chat/tree/main/apps/api/src/app/app.module.ts
https://github.com/roman-supy-io/soketi-chat/tree/main/apps/app/src/app/app.component.ts

**Expected behavior**
A Soketi server exits successfully, closing all the connections and not creating new ones.

**Screenshots**
Here's a GIF showing what's happening:
[https://imgur.com/bPWrH1Q](https://imgur.com/bPWrH1Q)
![image](https://user-images.githubusercontent.com/83349540/186202377-d6d9a2a1-6e9b-465e-9549-196dd9fb2d46.png)

**Environment**
- Soketi version: 1.4.0
- Adapter: redis
- App Manager : mysql
- Queue: sync
- Cache Managers: redis

**Configuration**
Run the server with `SOKETI_DEBUG=1` and paste the nested object configuration that outputs:
```js
{
  adapter: {
    driver: 'redis',
    redis: {
      requestsTimeout: 5000,
      prefix: 'soketi_',
      redisPubOptions: {},
      redisSubOptions: {},
      clusterMode: false
    },
    cluster: { requestsTimeout: 5000 },
    nats: {
      requestsTimeout: 5000,
      prefix: '',
      servers: [ '127.0.0.1:4222' ],
      user: null,
      pass: null,
      token: null,
      timeout: 10000,
      nodesNumber: null
    }
  },
  appManager: {
    driver: 'mysql',
    cache: { enabled: true, ttl: 60 },
    array: {
      apps: [
        {
          id: 'app-id',
          key: 'app-key',
          secret: 'app-secret',
          maxConnections: -1,
          enableClientMessages: false,
          enabled: true,
          maxBackendEventsPerSecond: -1,
          maxClientEventsPerSecond: -1,
          maxReadRequestsPerSecond: -1,
          webhooks: []
        }
      ]
    },
    dynamodb: { table: 'apps', region: 'us-east-1', endpoint: null },
    mysql: { table: 'apps', version: '8.0', useMysql2: true },
    postgres: { table: 'apps', version: '13.3' }
  },
  cache: { driver: 'memory', redis: { redisOptions: {}, clusterMode: false } },
  channelLimits: { maxNameLength: 100, cacheTtl: 60 },
  cluster: {
    hostname: '0.0.0.0',
    helloInterval: 500,
    checkInterval: 500,
    nodeTimeout: 2000,
    masterTimeout: 2000,
    port: 11002,
    prefix: '',
    ignoreProcess: true,
    broadcast: '255.255.255.255',
    unicast: null,
    multicast: null
  },
  cors: {
    credentials: true,
    origin: [ '*' ],
    methods: [ 'GET', 'POST', 'PUT', 'DELETE', 'OPTIONS' ],
    allowedHeaders: [
      'Origin',
      'Content-Type',
      'X-Auth-Token',
      'X-Requested-With',
      'Accept',
      'Authorization',
      'X-CSRF-TOKEN',
      'XSRF-TOKEN',
      'X-Socket-Id'
    ]
  },
  database: {
    mysql: {
      host: '127.0.0.1',
      port: 3306,
      user: 'root',
      password: 'password',
      database: 'mysql'
    },
    postgres: {
      host: '127.0.0.1',
      port: 5432,
      user: 'postgres',
      password: 'password',
      database: 'main'
    },
    redis: {
      host: '127.0.0.1',
      port: 6379,
      db: 0,
      username: null,
      password: null,
      keyPrefix: 'soketi_',
      sentinels: null,
      sentinelPassword: null,
      name: 'mymaster',
      clusterNodes: []
    }
  },
  databasePooling: { enabled: true, min: 0, max: 7 },
  debug: 1,
  eventLimits: {
    maxChannelsAtOnce: 100,
    maxNameLength: 100,
    maxPayloadInKb: 10,
    maxBatchSize: 10
  },
  host: '0.0.0.0',
  httpApi: { requestLimitInMb: 100, acceptTraffic: { memoryThreshold: 75 } },
  instance: { process_id: 34354 },
  metrics: {
    enabled: 1,
    driver: 'prometheus',
    host: '0.0.0.0',
    prometheus: { prefix: 'soketi_' },
    port: 9090
  },
  mode: 'full',
  port: 6001,
  pathPrefix: '',
  presence: { maxMembersPerChannel: 100, maxMemberSizeInKb: 1 },
  queue: {
    driver: 'redis',
    redis: { concurrency: 1, redisOptions: {}, clusterMode: false },
    sqs: {
      region: 'us-east-1',
      endpoint: null,
      clientOptions: {},
      consumerOptions: {},
      queueUrl: '',
      processBatch: false,
      batchSize: 1,
      pollingWaitTimeMs: 0
    }
  },
  rateLimiter: { driver: 'redis', redis: { redisOptions: {}, clusterMode: false } },
  shutdownGracePeriod: 10000,
  ssl: { certPath: '', keyPath: '', passphrase: '', caPath: '' },
  userAuthenticationTimeout: 5000,
  webhooks: { batching: { enabled: false, duration: 50 } }
}
  📡 soketi initialization....  
  ⚡ Initializing the HTTP API & Websockets Server...  
  ⚡ Initializing the Websocket listeners and channels...  
  ⚡ Initializing the HTTP webserver...  
  🕵️‍♂️ Initiating metrics endpoints...  

   🎉 Server is up and running!   
   📡 The Websockets server is available at 127.0.0.1:6001   
   🔗 The HTTP API server is available at http://127.0.0.1:6001   
   🎊 The /usage endpoint is available on port 9090.   
   🌠 Prometheus /metrics endpoint is available on port 9090.   

   [Tue Aug 23 2022 18:26:43 GMT+0300 (Eastern European Summer Time)] Promoted from node to master.   
{
  isMaster: true,
  isMasterEligible: true,
  weight: -0.1661268402512,
  address: '127.0.0.1',
  advertisement: undefined
}
```

**Additional context**
This is only reproducible with custom apps, with the test app everything works fine.

**Comment by rennokki** [comment]
I seem to find no related issues between diffs of the versions. Make sure you increase the [graceful shutdown period](https://docs.soketi.app/advanced-usage/graceful-shutdowns) to ensure no connections are stale.

Database might be holiding connections too much, or perhaps your running server does not respond to SIGINT/SIGTERM. Please re-open if this persists.
