### ISSUE TITLE
[BUG] Docker image 1.5.0-16-alpine (current latest) is broken

### ISSUE THREAD

**Issue by pavons** [soketi/soketi#741]
**Description**
The latest image is broken, this error is similar to https://github.com/soketi/soketi/issues/7

**Reproduction steps**
```
docker run --rm -it quay.io/soketi/soketi:1.5.0-16-alpine
```
or
```
docker run --rm -it quay.io/soketi/soketi:latest
```

**Expected behavior**
Service up and running

**Error Message**
```
/app/node_modules/uWebSockets.js/uws.js:22
                throw new Error('This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).\n\n' + e.toString());
                ^

Error: This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).

Error: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /app/node_modules/uWebSockets.js/uws_linux_x64_93.node)
    at /app/node_modules/uWebSockets.js/uws.js:22:9
    at Object.<anonymous> (/app/node_modules/uWebSockets.js/uws.js:24:3)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/app/dist/server.js:18:13)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
```

**Comment by rennokki** [comment]
Alpine images are deprecated either way, because uWS.js do not recommend Alpine Linux images: https://github.com/soketi/soketi/issues/449

Use the Debian variant, the latest version is way smaller than <1.5.0
