### ISSUE TITLE
[BUG] Running distroless images throws file permission errors

### ISSUE THREAD

**Issue by dbpolito** [soketi/soketi#849]
**Description**

Running distroless images throws file permission errors, not sure this breaks anything... debian works just fine

**Reproduction steps**

```bash
docker run quay.io/soketi/soketi:1.4-16-distroless
```

**Expected behavior**

**Screenshots**

```
docker run quay.io/soketi/soketi:1.5-16-distroless
Error: EACCES: permission denied, mkdir '/nonexistent/.pm2/logs'
    at Object.mkdirSync (node:fs:1382:3)
    at mkdirpNativeSync (/app/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/app/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/app/node_modules/pm2/lib/Client.js:133:25)
    at new module.exports (/app/node_modules/pm2/lib/Client.js:38:8)
    at new API (/app/node_modules/pm2/lib/API.js:107:19)
    at Object.<anonymous> (/app/node_modules/pm2/index.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
Error: EACCES: permission denied, mkdir '/nonexistent/.pm2/pids'
    at Object.mkdirSync (node:fs:1382:3)
    at mkdirpNativeSync (/app/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/app/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/app/node_modules/pm2/lib/Client.js:141:25)
    at new module.exports (/app/node_modules/pm2/lib/Client.js:38:8)
    at new API (/app/node_modules/pm2/lib/API.js:107:19)
    at Object.<anonymous> (/app/node_modules/pm2/index.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
Error: ENOENT: no such file or directory, open '/nonexistent/.pm2/module_conf.json'
    at Object.openSync (node:fs:590:3)
    at Object.writeFileSync (node:fs:2202:35)
    at module.exports.Client.initFileStructure (/app/node_modules/pm2/lib/Client.js:149:10)
    at new module.exports (/app/node_modules/pm2/lib/Client.js:38:8)
    at new API (/app/node_modules/pm2/lib/API.js:107:19)
    at Object.<anonymous> (/app/node_modules/pm2/index.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
Error: EACCES: permission denied, mkdir '/nonexistent/.pm2/modules'
    at Object.mkdirSync (node:fs:1382:3)
    at mkdirpNativeSync (/app/node_modules/mkdirp/lib/mkdirp-native.js:29:10)
    at Function.mkdirpSync [as sync] (/app/node_modules/mkdirp/index.js:21:7)
    at module.exports.Client.initFileStructure (/app/node_modules/pm2/lib/Client.js:157:25)
    at new module.exports (/app/node_modules/pm2/lib/Client.js:38:8)
    at new API (/app/node_modules/pm2/lib/API.js:107:19)
    at Object.<anonymous> (/app/node_modules/pm2/index.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
Error: ENOENT: no such file or directory, open '/nonexistent/.pm2/module_conf.json'
    at Object.openSync (node:fs:590:3)
    at Object.readFileSync (node:fs:458:35)
    at Object.Configuration.getAllSync (/app/node_modules/pm2/lib/Configuration.js:299:26)
    at Object.Configuration.getSync (/app/node_modules/pm2/lib/Configuration.js:270:30)
    at new API (/app/node_modules/pm2/lib/API.js:116:44)
    at Object.<anonymous> (/app/node_modules/pm2/index.js:11:18)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)

  🕵️‍♂️ Initiating metrics endpoints...

   🎉 Server is up and running!
   📡 The Websockets server is available at 127.0.0.1:6001
   🔗 The HTTP API server is available at http://127.0.0.1:6001
   🎊 The /usage endpoint is available on port 9601.
```

**Environment**
- Soketi version (i.e. 1.3.0): 1.5.0
- Adapter (local, redis): local
- App Manager (array, mysql, postgres, dynamodb) : array
- Queue (sqs, redis, sync): sync
- Cache Managers (memory, redis): memory

**Comment by amazing4u** [comment]
The problem is still there in soketi:1.6-16-distroless. setting home directory as described here: https://github.com/soketi/soketi/issues/367 does not help. 

Will soketi work unstable as described in the linked issue? Or can we ignore the problem?

**Comment by Spice-King** [comment]
I poked around, found that requiring PM2 at https://github.com/soketi/soketi/blob/5d188786beaf683aca2115a6247dcdc15c29ac77/src/rate-limiters/cluster-rate-limiter.ts#L8 causes the issue during the require as it boots PM2 up.

Poking around locally, it seems like this works as a hacky fix, and should be low impact.
```diff
diff --git a/src/rate-limiters/cluster-rate-limiter.ts b/src/rate-limiters/cluster-rate-limiter.ts
index c58c891..9e90eba 100644
--- a/src/rate-limiters/cluster-rate-limiter.ts
+++ b/src/rate-limiters/cluster-rate-limiter.ts
@@ -5,7 +5,7 @@ import { RateLimiterAbstract, RateLimiterClusterMasterPM2 } from 'rate-limiter-f
 import { Server } from '../server';
 
 const cluster = require('cluster');
-const pm2 = require('pm2');
+let pm2 = null;
 
 export interface ConsumptionMessage {
     app: App;
@@ -24,6 +24,7 @@ export class ClusterRateLimiter extends LocalRateLimiter {
         if (cluster.isPrimary || typeof cluster.isPrimary === 'undefined') {
             if (server.pm2) {
                 // With PM2, discovery is not needed.
+                pm2 ??= require('pm2');
                 new RateLimiterClusterMasterPM2(pm2);
             } else {
                 // When a new master is demoted, the rate limiters it has become the pivot points of the real, synced
```
On paper, should be possible to even ditch the `pm2` variable as `require` should always return the same value for a requested module, but that's a call for someone else to make.

**Comment by hosni** [comment]
I ran into the same “**EACCES**: **permission denied**, mkdir `/etc/.pm2/logs` error.

I solved it by mounting a [tmpfs](https://docs.docker.com/engine/storage/tmpfs/) for the PM2 home directory, so that it’s writable (in memory) and doesn’t try to write under `/etc`.

Here’s my Docker Compose snippet:
```yaml
soketi:
  image: quay.io/soketi/soketi:1.4-16-distroless
  restart: always
  environment:
    PM2_HOME: '/app/.pm2'
  tmpfs:
    - /app/.pm2:noexec,size=10m,mode=1777
```

With that:
* The `PM2_HOME` env var ensures PM2 uses `/app/.pm2` instead of `/etc/.pm2`.
* The `tmpfs` mount gives a writable ephemeral filesystem (10 MB here) at `/app/.pm2`, with `1777` mode so it’s world-writable (sticky bit).
* Thus PM2 can create logs, pids, etc. without permission issues.

Or you can run it using `docker run` with:
```bash
docker run -p 6001:6001 -e PM2_HOME="/app/.pm2" --tmpfs /app/.pm2:noexec,size=1024,mode=1777 quay.io/soketi/soketi:1.4-16-distroless
```

**Comment by amazing4u** [comment]
Nice. I can't use docker compose (i am using caprover), but with your idea this works also with a simple Dockerfile without tmpfs using /dev/shm/.pm2 (~64 MiB space):

```
FROM quay.io/soketi/soketi:1.6-16-distroless

ENV PM2_HOME=/dev/shm/.pm2
```

**Comment by hosni** [comment]
> Nice. I can't use docker compose (i am using caprover), but with your idea this works also with a simple Dockerfile without tmpfs using /dev/shm/.pm2 (~64 MiB space):
> 
> ```
> FROM quay.io/soketi/soketi:1.6-16-distroless
> 
> ENV PM2_HOME=/dev/shm/.pm2
> ```

Hi @amazing4u 
I didn’t know about [CapRover](https://caprover.com), that’s amazing!
I just tested the demo and noticed it actually supports [Docker Compose](https://caprover.com/docs/docker-compose.html).

But if your project doesn’t use it, then yeah, using the shared memory device is a great idea.
I’ve tested it as well and it works perfectly.
